---
fixtures:
  symlinks:
    profile: site/profile
    role: site/role
  forge_modules:
    inifile:
      repo: puppetlabs-inifile
      ref: 1.6.0
    stdlib:
      repo: puppetlabs-stdlib
      ref: 4.13.1
    concat:
      repo: puppetlabs-concat
      ref: 2.2.0
    apache:
      repo: puppetlabs-apache
      ref: 1.11.0
    tomcat:
      repo: puppetlabs-tomcat
      ref: 1.6.1
    ssh:
      repo: ghoneycutt-ssh
      ref: 3.49.0
    common:
      repo: ghoneycutt-common
      ref: 1.6.0
    firewall:
      repo: puppetlabs-firewall
      ref: 1.8.2
    java:
      repo: puppetlabs-java
      ref: 1.6.0
    ntp:
      repo: puppetlabs-ntp
      ref: 6.0.0
    staging:
      repo: puppet-staging
      ref: 2.2.0
    windows_env:
      repo: badgerious-windows_env
      ref: 2.2.2
    windows_java:
      repo: cyberious-windows_java
      ref: 1.0.2
    windows_disk_facts:
      repo: dylanratcliffe-windows_disk_facts
      ref: 0.1.1
    reboot:
      repo: puppetlabs-reboot
      ref: 1.2.1
    iis:
      repo: puppet-iis
      ref: 3.0.0
    download_file:
      repo: puppet-download_file
      ref: 2.1.0
    windowsfeature:
      repo: puppet-windowsfeature
      ref: 2.1.0
    registry:
      repo: puppetlabs-registry
      ref: 1.1.3
    wsus_client:
      repo: puppetlabs-wsus_client
      ref: 1.0.3
    acl:
      repo: puppetlabs-acl
      ref: 1.1.2
    dism:
      repo: puppetlabs-dism
      ref: 1.2.0
    powershell:
      repo: puppetlabs-powershell
      ref: 2.1.0
    chocolatey:
      repo: puppetlabs-chocolatey
      ref: 2.0.1
